-- MySQL Script generated by MySQL Workbench
-- Mon Jan 17 12:33:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projetoIntegrador` DEFAULT CHARACTER SET utf8 ;
USE `db_projetoIntegrador` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projetoIntegrador`.`tb_usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `col_nome` VARCHAR(255) NOT NULL,
  `col_email` VARCHAR(255) NOT NULL,
  `col_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projetoIntegrador`.`tb_tema` (
  `id_tema` BIGINT NOT NULL AUTO_INCREMENT,
  `col_tema` VARCHAR(50) NOT NULL,
  `col_descricao` VARCHAR(255) NULL,
  `col_destino` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projetoIntegrador`.`tb_postagens` (
  `id_postagem` BIGINT NOT NULL AUTO_INCREMENT,
  `col_titulo` VARCHAR(50) NULL,
  `col_descricao` VARCHAR(1000) NULL,
  `col_imagem` VARCHAR(255) NULL,
  `col_data_postagem` DATE NULL,
  `fk_usuario` BIGINT(20) NOT NULL,
  `fk_tema` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_tema_idx` (`fk_tema` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tema`
    FOREIGN KEY (`fk_tema`)
    REFERENCES `mydb`.`tb_tema` (`id_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


iNSERT INTO tb_usuarios(col_nome, col_email, col_senha) VALUES
("Karol", "karol@email.com", 123456),
("Paulo", "paulo@email.com", 12364560),
("Jess", "Jess@email.com", 1231321),
("Gustavo", "gustavo@email.com", 123456);

INSERT INTO tb_tema(col_tema, col_descricao, col_destino) VALUES
("Doação", "Doação de roupas ou suprimentos", "Empresa para ONG"),
("Doação",  "Doação de roupas ou suprimentos", "ONG para empresas"),
("Curso", "Capacitação de jovens","ONG para empresa");

INSERT INTO tb_postagens(col_titulo, col_descricao, col_data_postagem, fk_usuario, fk_tema) VALUES
("Doação para crianças de Diadema", "Texto explicando o rolê com os requisitos", "2022-1-17", 1, 1);

INSERT INTO tb_postagens(col_titulo, col_descricao, col_data_postagem, fk_usuario, fk_tema) VALUES
("Doação para crianças de Diadema", "Texto explicando o rolê com os requisitos", "2022-1-17", 4, 2),
("Doação para crianças de Diadema", "Texto explicando o rolê com os requisitos", "2022-1-17", 3, 1),
("Doação para crianças de Diadema", "Texto explicando o rolê com os requisitos", "2022-1-17", 2, 3);


select * from tb_postagens

